### ISSUE TITLE
App broken under wayland / Fedora 34

### ISSUE THREAD

**Issue by chrismin13** [chrismin13/enpass-snap#7]
On a Fedora 34 Beta install with GNOME 40:

```
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland-egl" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)
```

Still have to test under Ubuntu with wayland.

**Comment by rophelan21** [comment]
I can confirm this is broken in Ubuntu Hippo release as well.

**Comment by maks** [comment]
I've jusst runinto this installing Ubuntu 21.04 (Hippo) - is there at least even a work around?

**Comment by chrismin13** [comment]
The official repos found in the enpass website still work great. I'll be looking into this hopefully soon.

**Comment by maks** [comment]
@chrismin13 brillant thank you! I'd completely forgotten that you had you own apt repo which indeed works fine 👍🏻

**Comment by chrismin13** [comment]
I've pushed an update that disables wayland for the Snap. It should have hopefully automatically updated. If not, you can run `snap refresh enpass` to update manually. Please try it out and let me know if it works for you!

I've also noticed that the browser plugin still doesn't work. I'll have to reach out to the Enpass team to get that sorted, but I've temporarily pushed an older version to the Edge channel that still works. with the browser plugin. You can switch to that either from the store or with the command `snap refresh enpass --edge`
